services:
    # aliases to use as parent for concrete rendering services
    mds.pimprint.core.rendering_project: '@Mds\PimPrint\CoreBundle\Project\RenderingProject'
    mds.pimprint.core.master_locale_rendering_project: '@Mds\PimPrint\CoreBundle\Project\MasterLocaleRenderingProject'

    # aliases enabling auto wiring for type hints to our own implementations
    Mds\PimPrint\CoreBundle\Service\UserHelper: '@mds.pimprint.core.user_helper'
    Mds\PimPrint\CoreBundle\Service\PluginParameters: '@mds.pimprint.core.plugin_parameters'
    Mds\PimPrint\CoreBundle\Service\SpecialChars: '@mds.pimprint.core.special_chars'
    Mds\PimPrint\CoreBundle\Service\ImageDimensions: '@mds.pimprint.core.image_dimensions'
    Mds\PimPrint\CoreBundle\Service\ThumbnailHelper: '@mds.pimprint.core.thumbnail_helper'
